### ISSUE TITLE
escape codes in output

### ISSUE THREAD

**Issue by hugeping** [jhekasoft/instead-manager#2]
Please, make using of escape codes optional.
Currently, i have problems with piping managers output to other programs.

**Comment by jhekasoft** [comment]
Yes. I know about this problem and I will fix it.

**Comment by jhekasoft** [comment]
Fixed. I have added option `-ansi` with the one of values: `{on,off,auto}`. Default value is `auto` and it may recognize tty, so don't care about it and use command like below.

```
python3 instead-manager.py -l | less
```

But if you want to control it you can use `on` or `off` values. Example:

```
python3 instead-manager.py -l -ansi=off
```
